export { default as HomePageView } from "./HomePageView";
export { default as AllCampusesView } from "./AllCampusesView";
export { default as CampusView } from "./CampusView";
export { default as AllStudentsView } from "./AllStudentsView";
export { default as StudentView } from "./StudentView";
export { default as NewStudentView } from "./NewStudentView";
export { default as NewCampusView } from "./NewCampusView";
export { default as EditStudentView } from "./EditStudentView";
export { default as EditCampusView } from "./EditCampusView";